const fs = require('fs');

const fileMap = {
  'src/features/admin/LawyerForm.tsx': [
    ['Edit Lawyer', 'Редактировать адвоката'],
    ['Add New Lawyer', 'Добавить нового адвоката'],
    ['Update attorney profile details', 'Обновить профиль адвоката'],
    ['Create a new attorney profile', 'Создать новый профиль адвоката'],
    ['Basic Information', 'Основная информация'],
    ['Full Name *', 'Полное имя *'],
    ['e.g. Alexandra Reeves', 'напр. Александра Ривз'],
    ['Slug (URL handle) *', 'Слаг (URL) *'],
    ['e.g. alexandra-reeves', 'напр. alexandra-reeves'],
    ['Title / Position', 'Должность'],
    ['e.g. Senior Partner', 'напр. Старший партнер'],
    ['Years of Experience', 'Опыт работы (лет)'],
    ['e.g. 15', 'напр. 15'],
    ['Contact & Media', 'Контакты и медиа'],
    ['WhatsApp Phone *', 'Телефон WhatsApp *'],
    ['(E.164, no +)', '(без +)'],
    ['Photo URL', 'Ссылка на фото'],
    ['WhatsApp Default Message', 'Сообщение WhatsApp по умолчанию'],
    ['Hello, I would like to schedule a consultation.', 'Здравствуйте, я хотел бы записаться на консультацию.'],
    ['Profile Content', 'Профиль'],
    ['Biography', 'Биография'],
    ['Write a detailed professional biography…', 'Напишите подробную биографию...'],
    ['Education', 'Образование'],
    ['e.g. J.D., Harvard Law School', 'напр. МГУ'],
    ['Practice Area Assignment', 'Специализация'],
    ['First select a parent category, then select specific sub-services to assign to this attorney.', 'Сначала выберите категорию, затем выберите услуги.'],
    ['1. Parent Category', '1. Основная категория'],
    ['— Select a category —', '— Выберите категорию —'],
    ['2. Sub-services', '2. Подуслуги'],
    ['(select all that apply)', '(выберите все подходящие)'],
    ['service assigned', 'услуг назначено'],
    ['services assigned', 'услуг назначено'],
    ['Click to remove', 'Нажмите, чтобы удалить'],
    ['Active Profile', 'Активный профиль'],
    ['Inactive lawyers are hidden from the public site', 'Неактивные адвокаты скрыты с сайта'],
    ['Update Lawyer', 'Обновить адвоката'],
    ['Create Lawyer', 'Создать адвоката'],
    ['Cancel', 'Отмена'],
    ['Lawyer updated successfully', 'Адвокат успешно обновлен'],
    ['Lawyer created successfully', 'Адвокат успешно создан'],
    ['Failed to save. Please check all fields.', 'Ошибка сохранения. Проверьте поля.'],
  ],
  'src/features/admin/LawyerList.tsx': [
    ['Manage Lawyers', 'Управление адвокатами'],
    ['Add, edit, or remove attorney profiles.', 'Добавлять, изменять и удалять профили адвокатов.'],
    ['Add Lawyer', 'Добавить адвоката'],
    ['Delete Lawyer', 'Удалить адвоката'],
    ['Are you sure you want to delete', 'Вы уверены, что хотите удалить'],
    ["This action cannot be undone.", "Это действие нельзя отменить."],
    ['Lawyer deleted successfully', 'Адвокат успешно удален'],
    ['Failed to delete lawyer', 'Не удалось удалить адвоката'],
    ['Active', 'Активен'],
    ['Inactive', 'Неактивен'],
    ['Search by name...', 'Поиск по имени...'],
    ['All Status', 'Все статусы'],
    ['Lawyer', 'Адвокат'],
    ['Experience', 'Опыт'],
    ['Status', 'Статус'],
    ['Actions', 'Действия'],
    ['Edit', 'Редактировать'],
    ['Delete', 'Удалить'],
    ['years', 'лет'],
    ['No lawyers found.', 'Адвокаты не найдены.'],
  ],
  'src/features/admin/ServiceForm.tsx': [
    ['Edit Service', 'Редактировать услугу'],
    ['Add New Service', 'Добавить новую услугу'],
    ['Update service details', 'Обновить данные услуги'],
    ['Create a new service offering', 'Создать новую услугу'],
    ['Basic Information', 'Основная информация'],
    ['Service Name *', 'Название услуги *'],
    ['e.g. Corporate Restructuring', 'напр. Корпоративное право'],
    ['Slug (URL handle) *', 'Слаг (URL) *'],
    ['e.g. corporate-restructuring', 'напр. corporate-law'],
    ['Description', 'Описание'],
    ['Brief overview of this legal service...', 'Краткое описание услуги...'],
    ['Hierarchy & Organization', 'Иерархия'],
    ['Parent Service', 'Родительская услуга'],
    ['— None (Top Level Category) —', '— Нет (Главная категория) —'],
    ['Only top-level services can have children.', 'Только главные услуги могут иметь дочерние.'],
    ['Display Order', 'Порядок отображения'],
    ['Lower numbers appear first', 'Меньшие числа отображаются первыми'],
    ['Status Settings', 'Статус'],
    ['Active Service', 'Активная услуга'],
    ['Inactive services are hidden from the public site', 'Неактивные услуги скрыты с сайта'],
    ['Update Service', 'Обновить услугу'],
    ['Create Service', 'Создать услугу'],
    ['Cancel', 'Отмена'],
    ['Service updated successfully', 'Услуга успешно обновлена'],
    ['Service created successfully', 'Услуга успешно создана'],
  ],
  'src/features/admin/ServiceList.tsx': [
    ['Manage Services', 'Управление услугами'],
    ['Organize your firm\'s practice areas and sub-services.', 'Организуйте услуги компании.'],
    ['Add Service', 'Добавить услугу'],
    ['Delete Service', 'Удалить услугу'],
    ['Are you sure you want to delete', 'Вы уверены, что хотите удалить'],
    ['This action cannot be undone.', 'Это действие нельзя отменить.'],
    ['Service deleted successfully', 'Услуга успешно удалена'],
    ['Failed to delete service', 'Не удалось удалить услугу'],
    ['All Parents', 'Все родительские'],
    ['Top Level Only', 'Только главные'],
    ['Service Name', 'Название услуги'],
    ['Parent', 'Родитель'],
    ['Status', 'Статус'],
    ['Actions', 'Действия'],
    ['Edit', 'Редактировать'],
    ['Delete', 'Удалить'],
    ['Top Level', 'Главная'],
    ['No services found.', 'Услуги не найдены.'],
  ],
};

Object.entries(fileMap).forEach(([file, replacements]) => {
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, 'utf8');
    replacements.forEach(([eng, rus]) => {
      // Escape for regex and do global replace
      const regex = new RegExp(eng.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
      content = content.replace(regex, rus);
    });
    fs.writeFileSync(file, content, 'utf8');
    console.log(`Updated ${file}`);
  }
});
